demosite = "https://willfaught.com/paige"
description = "Powerful, pliable pixel perfection. An advanced Hugo theme."
features = [
  "accessibility",
  "analytics",
  "atom feed",
  "authors",
  "blog",
  "bootstrap styles and icons",
  "categories",
  "code shortcode",
  "comments",
  "customizable",
  "dark color scheme",
  "email shortcode",
  "facebook sharing",
  "figure shortcode",
  "gallery shortcode",
  "header links",
  "icon shortcode",
  "image pixel densities",
  "image shortcode",
  "image size breakpoints",
  "image thumbnails",
  "landing page",
  "languages",
  "light color scheme",
  "math typesetting",
  "menu",
  "minimal design",
  "quote shortcode",
  "responsive",
  "right-to-left languages",
  "rss feed",
  "safari and firefox reader view support",
  "search",
  "sections",
  "seo",
  "series",
  "single column",
  "social links",
  "tab shortcode",
  "table of contents",
  "tags",
  "twitter sharing",
  "validated",
  "vimeo shortcode",
  "youtube shortcode",
]
homepage = "https://github.com/willfaught/paige"
license = "MIT"
licenselink = "https://github.com/willfaught/paige/blob/master/LICENSE"
name = "Paige"
tags = [
  "archive",
  "blog",
  "bootstrap",
  "company",
  "contact",
  "dark mode",
  "dark",
  "docs",
  "gallery",
  "hero",
  "landing",
  "light",
  "minimal",
  "multilingual",
  "personal",
  "podcast",
  "portfolio",
  "responsive",
]

[author]
homepage = "https://willfaught.com"
name = "Will Faught"
