baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Práctica 1 de HUGO'
contentDir = "content"
theme = "paige"
ignoreLogs = ['warning-goldmark-raw-html']
[menu]
[[menu.main]]
  name = "Hablando de mí"
  url = "./"
  weight = 1

[[menu.main]]
  name = "Markdown Básico"
  url = "/markdown/basico"
  weight = 2

[[menu.main]]
    name = "Markdown gráficos y extendido"
    url = "/markdown/avanzado"
    weight = 3

[[menu.main]]
  name = "TV"
  url = "/tv/"
  weight = 4

 [[menu.main]]
   name = "Viaje a Suiza"
   url = "/Verano en Suiza/"
   weight = 5

[[menu.main]]
   name = "Apuntes CSS"
   url = "/CSS/"
   weight = 6

[markup.goldmark.renderer]
      unsafe = true
